#!/usr/bin/env python3
"""Interactively calibrate Manus ergonomics to safe Wuji joint commands."""

from __future__ import annotations

import argparse
import os
import sys
import threading
import time
from pathlib import Path
from typing import Any

import rclpy
import yaml
from rclpy.node import Node

from calibration_math import build_side_config, median_pose
from joint_map import ergonomics_list_to_dict, load_retarget_config

try:
    from manus_ros2_msgs.msg import ManusGlove
except ImportError as exc:
    raise SystemExit(
        "manus_ros2_msgs not found. Source ROS2 and ~/ros2_ws/install/setup.bash first."
    ) from exc


POSE_PROMPTS = (
    ("open", "先自然张开手掌并伸直手指"),
    ("fist", "先握好拳，让所有手指处于舒适最大弯曲位置"),
    ("together", "先伸直并拢手指（拇指也向掌侧收拢）"),
    ("spread", "先伸直手指并尽量张开"),
)


class ErgonomicsCollector(Node):
    def __init__(self) -> None:
        super().__init__("manus_calibration")
        self.latest: dict[str, dict[str, float]] = {}
        self._lock = threading.Lock()
        self._subscribed: set[str] = set()
        self._discover_topics()
        self.create_timer(1.0, self._discover_topics)

    def _discover_topics(self) -> None:
        for name, types in self.get_topic_names_and_types():
            if (
                name.startswith("/manus_glove_")
                and not name.endswith("/vibration_cmd")
                and "manus_ros2_msgs/msg/ManusGlove" in types
                and name not in self._subscribed
            ):
                self.create_subscription(ManusGlove, name, self._on_glove, 10)
                self._subscribed.add(name)
                self.get_logger().info(f"Subscribed to {name}")

    def _on_glove(self, msg: ManusGlove) -> None:
        side = (msg.side or "").lower()
        if side not in ("left", "right"):
            return
        pose = ergonomics_list_to_dict(msg.ergonomics)
        if pose:
            with self._lock:
                self.latest[side] = pose

    def available_sides(self) -> set[str]:
        with self._lock:
            return set(self.latest)

    def sample_pose(self, side: str, duration: float) -> dict[str, float]:
        samples: list[dict[str, float]] = []
        deadline = time.monotonic() + duration
        while time.monotonic() < deadline:
            with self._lock:
                pose = self.latest.get(side)
                if pose:
                    samples.append(dict(pose))
            time.sleep(1.0 / 60.0)
        if not samples:
            raise RuntimeError(f"未收到 {side} 手套数据")
        return median_pose(samples)


def parse_args() -> argparse.Namespace:
    root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description="交互式 Manus → Wuji 标定")
    parser.add_argument("--side", choices=("left", "right", "both"), default="both")
    parser.add_argument("--duration", type=float, default=3.0, help="每个姿态采样秒数")
    parser.add_argument(
        "--min-input-delta",
        type=float,
        default=2.0,
        help="Manus 通道最小有效变化量，默认 2.0",
    )
    parser.add_argument(
        "--base-config",
        type=Path,
        default=root / "examples" / "retarget_manus_to_wuji.yaml",
        help="保留未标定手配置的基础 YAML",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=root / "examples" / "retarget_manus_to_wuji.calibrated.yaml",
    )
    parser.add_argument("--force", action="store_true", help="允许覆盖输出文件")
    return parser.parse_args()


def wait_for_sides(node: ErgonomicsCollector, sides: list[str]) -> None:
    print("等待 Manus 手套数据", end="", flush=True)
    deadline = time.monotonic() + 30.0
    while time.monotonic() < deadline:
        if set(sides).issubset(node.available_sides()):
            print(" 就绪")
            return
        print(".", end="", flush=True)
        time.sleep(0.5)
    print()
    missing = sorted(set(sides) - node.available_sides())
    raise RuntimeError(f"30 秒内未收到手套数据：{', '.join(missing)}")


def capture_side(
    node: ErgonomicsCollector, side: str, duration: float
) -> dict[str, dict[str, float]]:
    side_name = "左手" if side == "left" else "右手"
    print(f"\n开始标定{side_name}。采集时保持姿态稳定。")
    poses: dict[str, dict[str, float]] = {}
    for key, prompt in POSE_PROMPTS:
        input(f"\n请{prompt}；动作完全做好后按 Enter：")
        print(f"采集中（{duration:.1f} 秒），请保持不动...", flush=True)
        poses[key] = node.sample_pose(side, duration)
        print("完成")
    return poses


def save_config(path: Path, config: dict[str, Any], force: bool) -> None:
    if path.exists() and not force:
        raise FileExistsError(f"{path} 已存在；换一个 --output 或添加 --force")
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = path.with_suffix(path.suffix + ".tmp")
    with temp_path.open("w", encoding="utf-8") as stream:
        stream.write("# Generated by x86/calibrate_manus.py; angles are radians.\n")
        yaml.safe_dump(config, stream, sort_keys=False, allow_unicode=True)
    os.replace(temp_path, path)


def main() -> int:
    args = parse_args()
    if args.duration <= 0:
        raise SystemExit("duration 必须大于 0")

    sides = ["left", "right"] if args.side == "both" else [args.side]
    config = load_retarget_config(args.base_config)
    config.pop("notes", None)

    rclpy.init()
    node = ErgonomicsCollector()
    spin_thread = threading.Thread(target=rclpy.spin, args=(node,), daemon=True)
    spin_thread.start()
    try:
        wait_for_sides(node, sides)
        print(
            "\n此过程不会连接或驱动 Wuji。映射保持角度一比一；"
            "标定只计算方向和零位。"
        )
        for side in sides:
            poses = capture_side(node, side, args.duration)
            side_config, errors = build_side_config(
                poses["open"],
                poses["fist"],
                poses["together"],
                poses["spread"],
                min_input_delta=args.min_input_delta,
            )
            if errors:
                details = "\n  - ".join(errors)
                raise RuntimeError(
                    f"{side} 标定失败，以下通道动作幅度不足或缺失：\n  - {details}\n"
                    "请重跑并更清楚地完成对应动作。"
                )
            config[side] = side_config

        config["calibration"] = {
            "created_unix": int(time.time()),
            "method": "four_pose_angle_preserving",
            "scale_magnitude": "pi/180",
        }
        save_config(args.output, config, args.force)
        print(f"\n标定完成：{args.output}")
        print("先单手、单指、急停就绪后再用此配置低速测试。")
        print(f"运行参数：--config {args.output}")
        return 0
    except (RuntimeError, FileExistsError) as exc:
        print(f"\n错误：{exc}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("\n已取消")
        return 130
    finally:
        rclpy.shutdown()
        spin_thread.join(timeout=2.0)
        node.destroy_node()


if __name__ == "__main__":
    sys.exit(main())
